# Site settings
baseurl = "http://dc2020.netlify.com/" # Change this to the base url after netlify deploy, e.g. "https://cardiff2019.satrdays.org/"
languageCode = "en-us"
title = "satRday"
theme = ["hugo-satrdays-theme", "hugo-agency-theme"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Disable taxonomies that are not used https://discourse.gohugo.io/t/found-no-layout-for-taxonomyterm-language-en-output-format-html/16376
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "satRday DC"
  description = "R conference in Washington, DC!"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = ["css/satrday.css"]
  custom_js  = []
  favicon    = "img/favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "satRday"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    services = "About"
    portfolio = "Talks"
    eventbrite = "Register"
    schedule = "Schedule"
    team = "People"
    contact = "Get involved"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://satrdays.org/"
      name = "satRdays.org"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "satRday DC"
    subtitle = "A conference for users of the R Language on March, 28th"
    bg = true
    buttonText = "Tell me more"


  # About [Services] section
  [params.services]
    enable = true
    title = "About"
    subtitle = "An accessible conference held at the capital city of the United States of America!"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-clock-o"
      title = "Details"
      description = "March 28th at George Washington University"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Hands on"
      description = "Practical applications and workshop sessions"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Learning"
      description = "Gain knowledge from your peers and experienced professionals"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Community Lead"
      description = "Community organised, community focused"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-money"
      title = "Affordable"
      description = "Only $25 for students and $50 for professionals (inquire for scholarships)"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-universal-access"
      title = "Accessible"
      description = "Inclusive, supportive and respectful environment"
      url = "#"

  # Register section
  # You only need ONE of these active
  [params.tito]
    enable = false
    title = "Register"
    bg = true
    accountevent = "ultimateconf/2013"
      # Go to https://ti.to/ and find the account (under your user) and event pair string e.g. "cardiff-satrday/2018"
      # include botht the account and event in a string, seperated by /, with no spaces

  [params.eventbrite]
    enable = false
    title = "Register"
    bg = true
    eid = "89940092237" 
      # Go to https://www.eventbrite.co.uk/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_GB 
      # Follow instructions to discover your 'Website Integration' embeddable iframe
      # Take ONLY the numeric string between "eid=" and "&ref=etckt"
      # Supply this string as the value to `eid` above

  [params.tickettailor]
    enable = false
    title = "Register"
    bg = true
    eventviewid = "162430"
      # Go to www.tickettailor.com and open your event page
      # Note the number at the end of the url e.g. https://www.tickettailor.com/event/view/id/162430
      # Supply the number ONLY in `eventviewid`
  
  # Call for papers section
  [params.callforpapers]
    enable = false
    title = "Call For Talks"
    bg = false
    CfSpage = "/satrdays-dc-2020"
      # Go to Organizer > My Events > Dashboard and copy the "CfS Page" string into the `CfSpage` value
    dates = "15 January - 28 February 2020"
  
  # Hackathon section
#  [params.hackathon]
#    enable = false
#    bg = false
#    title = "Hackathon"
#    subtitle="Can you _Hack_ it?"
#    brief1="You _can_ put markdown in the briefs section" 
#    brief2="But you __MUST__ hardcode html links <a href= 'www.google.com' > google  </a> for further info."
#    location= "The place we're going it"
#    dates = "15 November 2019"
#    times= "13:00-17:30"  
#    website_name="google"
#    website_url="www.google.com"

  # Talk [Portfolio] section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Speakers"
    subtitle = ""
    bg = true

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"

  # Schedule section
  [params.schedule]
    enable = false
    title = "Schedule"
    bg = false

  # Important Dates [About] section
  [params.about]
    enable = true
    title = "Important Dates"
    subtitle = "Be prepared!"
    endpoint = "Conference"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "fireworks_resized.jpg"
      date = "January, 15th 2020"
      title = "Call for talks begin"
      description = "We'd love to hear your ideas for talks!"

    [[params.about.events]]
      img = "valentines_resized.jpg"
      date = "February, 28th 2020"
      title = "Call for talks end"
      description = "Make sure to submit your ideas before this date!"

    [[params.about.events]]
      img = "clover_resized.png"
      date = "March, 7th, 2020"
      title = "Talks accepted"
      description = "This site will be updated with the accepted talks."

    [[params.about.events]]
      img = "cherryblossom_resized.jpg"
      date = "March, 28th 2020"
      title = "The big day!"
      description = "This will be an awesome event!"
  
  # Location section
  [params.location]
    enable = true
    title = "Location title"
    bg = true
    iframesrc = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3105.1149064660785!2d-77.05164598464958!3d38.89848757957053!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89b7b7b1c03df189%3A0xf75404628c052d5f!2sNorma%20Lee%20and%20Morton%20Funger%20Hall!5e0!3m2!1sen!2sus!4v1579060914225!5m2!1sen!2sus"

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Team"
    subtitle = "The people putting it together"
    bg = false
    description = ""
    speakers = ""
    

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "O_Briant_Kelly_resized.jpg"
      name = "Kelly O'Briant"
      position = ""
      reportsTo = ""
#      livesIn = "[Munich, Germany](#some-maps-url)"
#      scope = [
#        "Role 1 for [thing 1](#)",
#        "Role 2 for [thing 2](#)",
#        "Role 3 for [thing 3](#)"
#      ]
      # For bio markdown and even multiline strings are available.
      bio = """Co-organizer [R-Ladies DC](https://twitter.com/RLadiesDC)"""
      social = [
        ["fa-twitter", "https://twitter.com/kellrstats"],
        ["fa-github", "https://github.com/kellobri"]
      ]

    [[params.team.members]]
      img = "Ortiz_Ulloa_Benjamin_resized.jpg"
      name = "Benjamin Ortiz Ulloa"
      bio = """Co-organizer of [Data Viz DC](https://www.meetup.com/Data-Visualization-DC/) and [Data Community DC](https://twitter.com/datacommunitydc?lang=en)"""
      position = ""
      social = [
        ["fa-twitter", "https://twitter.com/plzbeemyfriend"],
        ["fa-github", "https://github.com/benjaminortizulloa"]
      ]


  # Client section
  [params.clients_list]
    enable = true
    # Possibility to center items
    #center = true
    # Optional client title specifying the involvement
    title = "Sponsors"
    bg = true

    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    # Suggestion: .svg in the size of 280px*80px looks good
    [[params.clients]]
      logo = "microsoft.png"
      link = "#"
  
  [params.diversity]
    enable = true
    title = "Diversity"
    bg = true

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
 #   subtitle  = "Lorem ipsum dolor sit amet consectetur."
 #   buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "ben@datacommunitydc.org"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/satrdays_org"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/satRdays"
      title = "GitHub"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
